import { genId, databaseService, ALL_COLLECTIONS } from "@/lib/services/databaseService";
import {
  Project,
  ShootDay,
  ProductionItem,
  Person,
  CastingRecord,
  Location,
  BudgetLine,
  CallSheet,
  Acknowledgement,
  ProductionTask,
  ActivityEntry,
} from "@/lib/types";

// Loads the Dixtro Inc. / DATE WITH MYA demo dataset into the given workspace.
export function loadDemoData(workspaceId: string) {
  const now = new Date().toISOString();

  // People
  const mya: Person = { id: genId("p"), workspaceId, name: "Mya", email: "mya@dixtro.demo", role: "Executive Producer", department: "Talent" };
  const woye: Person = { id: genId("p"), workspaceId, name: "Woye", email: "woye@dixtro.demo", role: "Producer", department: "Production" };
  const dayo: Person = { id: genId("p"), workspaceId, name: "Dayo", email: "dayo@dixtro.demo", role: "Camera Operator", department: "Camera" };
  const ada: Person = { id: genId("p"), workspaceId, name: "Ada", email: "ada@dixtro.demo", role: "Camera Operator", department: "Camera" };
  const people: Person[] = [mya, woye, dayo, ada];
  databaseService.bulkCreate("people", people);

  // Project 1: DATE WITH MYA
  const dwm: Project = {
    id: genId("proj"),
    workspaceId,
    name: "DATE WITH MYA",
    type: "TV",
    description: "8 episode dating show. 4 episodes per shoot day.",
    producer: "Woye",
    executiveProducer: "Mya",
    startDate: "2026-08-29",
    status: "Pre-Production",
    isEpisodic: true,
    notes: "Sound and Casting Director still TBD.",
    createdAt: now,
  };

  // Project 2: POP THE BALLOON
  const ptb: Project = {
    id: genId("proj"),
    workspaceId,
    name: "POP THE BALLOON",
    type: "YouTube",
    description: "8 episodes. Shoot dates TBD.",
    producer: "Woye",
    status: "Development",
    isEpisodic: true,
    createdAt: now,
  };

  databaseService.bulkCreate("projects", [dwm, ptb]);

  // Shoot day for DWM: 29 Aug 2026, 4 episodes
  const day1: ShootDay = {
    id: genId("day"),
    workspaceId,
    projectId: dwm.id,
    date: "2026-08-29",
    dayNumber: 1,
    callTime: "08:00",
    wrapTime: "20:00",
  };
  databaseService.bulkCreate("shootDays", [day1]);

  // Locations
  const loc1: Location = {
    id: genId("loc"),
    workspaceId,
    projectId: dwm.id,
    name: "Rooftop Studio, Lekki",
    address: "TBD",
    shootDayId: day1.id,
    status: "Shortlisted",
    notes: "Awaiting contract signature",
  };
  databaseService.bulkCreate("locations", [loc1]);

  // Episodes 1-4 for day 1, episodes 5-8 unscheduled (2 TBD slots + rest)
  const titles = ["Breakfast", "Brunch", "Lunch", "Dinner", "Movie Night", "Coffee Date", "TBD", "Season Finale"];
  const items: ProductionItem[] = titles.map((title, idx) => ({
    id: genId("item"),
    workspaceId,
    projectId: dwm.id,
    shootDayId: idx < 4 ? day1.id : undefined,
    number: idx + 1,
    title: idx < 6 || idx === 7 ? title : "TBD",
    locationId: idx < 4 ? loc1.id : undefined,
    castIds: [],
    crewIds: idx < 4 ? [dayo.id, ada.id, woye.id] : [],
    status: idx < 4 ? "Ready" : "Planned",
  }));
  databaseService.bulkCreate("productionItems", items);

  // Casting: Mya is host/EP (confirmed), guest cast still needed
  const casting: CastingRecord[] = [
    {
      id: genId("cast"),
      workspaceId,
      projectId: dwm.id,
      personId: mya.id,
      characterOrRole: "Host",
      itemId: items[0].id,
      status: "Confirmed",
    },
    {
      id: genId("cast"),
      workspaceId,
      projectId: dwm.id,
      characterOrRole: "Date #1 (Ep 1-4)",
      itemId: items[0].id,
      status: "Sourcing",
    },
  ];
  databaseService.bulkCreate("casting", casting);

  // Budget - intentionally left mostly unset to demonstrate "Budget not set" gap detection
  const budget: BudgetLine[] = [
    { id: genId("bud"), workspaceId, projectId: dwm.id, category: "Crew", label: "Camera team (Day 1)", estimated: 350000, actual: 0 },
  ];
  databaseService.bulkCreate("budgetLines", budget);

  // Tasks (auto-generated gaps)
  const tasks: ProductionTask[] = [
    { id: genId("task"), workspaceId, projectId: dwm.id, label: "Assign sound recordist", status: "Open", autoGenerated: true, relatedType: "crew", createdAt: now },
    { id: genId("task"), workspaceId, projectId: dwm.id, label: "Assign casting director", status: "Open", autoGenerated: true, relatedType: "crew", createdAt: now },
    { id: genId("task"), workspaceId, projectId: dwm.id, label: "Secure Rooftop Studio location", status: "Open", autoGenerated: true, relatedType: "location", createdAt: now },
    { id: genId("task"), workspaceId, projectId: dwm.id, label: "Generate call sheet for 29 Aug", status: "Open", autoGenerated: true, relatedType: "callsheet", createdAt: now },
  ];
  databaseService.bulkCreate("tasks", tasks);

  // Activity
  const activity: ActivityEntry[] = [
    { id: genId("act"), workspaceId, projectId: dwm.id, message: "Demo data loaded for DATE WITH MYA", createdAt: now },
  ];
  databaseService.bulkCreate("activity", activity);

  return { projects: [dwm, ptb] };
}

export function resetWorkspace(workspaceId: string) {
  databaseService.clearWorkspace(ALL_COLLECTIONS, workspaceId);
}
