// Core domain types for Production OS
// Every production-related record is scoped to a workspaceId.

export type Role = "Owner" | "Producer" | "Member";

export interface User {
  id: string;
  name: string;
  email: string;
}

export interface Workspace {
  id: string;
  name: string;
  logo?: string;
  timezone: string;
  ownerId: string;
  isDemo?: boolean;
  callSheetHoursBefore: number; // default 48
  reminderHoursBefore: number; // default 24
  finalReminderHoursBefore: number; // default 3
  callSheetEnabled: boolean;
  reminderEnabled: boolean;
  finalReminderEnabled: boolean;
  createdAt: string;
}

export interface Membership {
  id: string;
  workspaceId: string;
  userId: string;
  role: Role;
}

export type ProductionType =
  | "Film"
  | "Commercial"
  | "YouTube"
  | "TV"
  | "Documentary"
  | "Music Video"
  | "Social Content"
  | "Other";

export type ProjectStatus =
  | "Development"
  | "Pre-Production"
  | "Production"
  | "Post-Production"
  | "Completed"
  | "Archived";

export interface Project {
  id: string;
  workspaceId: string;
  name: string;
  type: ProductionType;
  description?: string;
  producer?: string;
  director?: string;
  executiveProducer?: string;
  startDate?: string;
  endDate?: string;
  status: ProjectStatus;
  notes?: string;
  isEpisodic: boolean; // controls "Episode" vs "Scene" language
  createdAt: string;
}

export type ItemStatus = "Planned" | "Ready" | "Shooting" | "Completed";

export interface ShootDay {
  id: string;
  workspaceId: string;
  projectId: string;
  date: string; // ISO date
  dayNumber: number;
  callTime?: string;
  wrapTime?: string;
  notes?: string;
}

export interface ProductionItem {
  // an "Episode" or "Scene" depending on project.isEpisodic
  id: string;
  workspaceId: string;
  projectId: string;
  shootDayId?: string;
  number: number;
  title: string;
  description?: string;
  time?: string;
  locationId?: string;
  castIds: string[];
  crewIds: string[];
  status: ItemStatus;
  notes?: string;
}

export type PersonRole =
  | "Producer"
  | "Executive Producer"
  | "Director"
  | "DOP"
  | "Camera Operator"
  | "Camera Assistant"
  | "Sound"
  | "Gaffer"
  | "Production Designer"
  | "Casting Director"
  | "Editor"
  | "Production Assistant"
  | "Cast"
  | "Other";

export interface Person {
  id: string;
  workspaceId: string;
  name: string;
  email?: string;
  phone?: string;
  role: PersonRole;
  department?: string;
  notes?: string;
}

export interface ProjectAssignment {
  id: string;
  workspaceId: string;
  projectId: string;
  personId: string;
  role: PersonRole;
  shootDayIds?: string[];
}

export type CastingStatus =
  | "Needed"
  | "Sourcing"
  | "Shortlisted"
  | "Awaiting Confirmation"
  | "Confirmed"
  | "Backup"
  | "Declined";

export interface CastingRecord {
  id: string;
  workspaceId: string;
  projectId: string;
  personId?: string;
  characterOrRole: string;
  itemId?: string; // episode/scene
  status: CastingStatus;
  contact?: string;
  notes?: string;
}

export type LocationStatus = "TBD" | "Shortlisted" | "Contacted" | "Confirmed" | "Secured";

export interface Location {
  id: string;
  workspaceId: string;
  projectId: string;
  name: string;
  address?: string;
  contact?: string;
  shootDayId?: string;
  itemId?: string;
  status: LocationStatus;
  cost?: number;
  notes?: string;
}

export type BudgetCategory =
  | "Crew"
  | "Cast"
  | "Location"
  | "Equipment"
  | "Transport"
  | "Catering"
  | "Production Design"
  | "Wardrobe"
  | "Post Production"
  | "Miscellaneous";

export interface BudgetLine {
  id: string;
  workspaceId: string;
  projectId: string;
  category: BudgetCategory;
  label: string;
  estimated: number;
  actual: number;
}

export interface CallSheet {
  id: string;
  workspaceId: string;
  projectId: string;
  shootDayId: string;
  generatedAt: string;
  sentAt?: string;
  recipients: string[]; // personIds
}

export type AckStatus = "Not Sent" | "Sent" | "Opened" | "Acknowledged" | "No Response";

export interface Acknowledgement {
  id: string;
  workspaceId: string;
  callSheetId: string;
  personId: string;
  status: AckStatus;
  updatedAt: string;
}

export type TaskStatus = "Open" | "Done";

export interface ProductionTask {
  id: string;
  workspaceId: string;
  projectId: string;
  label: string;
  status: TaskStatus;
  autoGenerated: boolean;
  relatedType?: "location" | "casting" | "crew" | "callsheet" | "communication" | "budget";
  createdAt: string;
}

export interface ActivityEntry {
  id: string;
  workspaceId: string;
  projectId: string;
  message: string;
  createdAt: string;
}

export interface ReadinessCheck {
  key: "schedule" | "crew" | "casting" | "location" | "budget" | "callSheet" | "communication" | "acknowledgement";
  label: string;
  ok: boolean;
  detail?: string;
}

export interface ReadinessResult {
  ready: boolean;
  checks: ReadinessCheck[];
  issueCount: number;
}
