"use client";

import { useState } from "react";
import { ProjectBundle, nextShootDay, readinessForShootDay } from "@/lib/data-hooks";
import { Card, CheckRow, StatusTag, Textarea, Button } from "@/components/ui/primitives";
import { aiService } from "@/lib/services/aiService";

export function OverviewTab({ bundle }: { bundle: ProjectBundle }) {
  const upcoming = [...bundle.shootDays].filter((d) => d.date >= new Date().toISOString().slice(0, 10)).sort((a, b) => a.date.localeCompare(b.date));
  const openTasks = bundle.tasks.filter((t) => t.status === "Open");

  return (
    <div className="grid lg:grid-cols-3 gap-5">
      <div className="lg:col-span-2 space-y-5">
        <Card className="p-4">
          <h3 className="text-sm font-semibold text-[var(--slate-500)] uppercase tracking-wide mb-3">Upcoming Shoots</h3>
          {upcoming.length === 0 ? (
            <p className="text-sm text-[var(--slate-500)]">No shoot days scheduled yet.</p>
          ) : (
            <div className="space-y-3">
              {upcoming.map((day) => {
                const readiness = readinessForShootDay(bundle, day);
                const items = bundle.items.filter((i) => i.shootDayId === day.id);
                return (
                  <div key={day.id} className="border border-[var(--slate-100)] rounded-lg p-3">
                    <div className="flex items-center justify-between mb-2">
                      <p className="font-mono-data text-sm font-medium">{day.date}</p>
                      <StatusTag tone={readiness.ready ? "good" : "warn"}>{readiness.ready ? "Ready" : `${readiness.issueCount} need attention`}</StatusTag>
                    </div>
                    <p className="text-xs text-[var(--slate-500)] mb-2">{items.length} {bundle.project.isEpisodic ? "episodes" : "scenes"}</p>
                    <div className="grid grid-cols-2 gap-x-4">
                      {readiness.checks.map((c) => (
                        <CheckRow key={c.key} ok={c.ok} label={c.label} />
                      ))}
                    </div>
                  </div>
                );
              })}
            </div>
          )}
        </Card>

        <Card className="p-4">
          <h3 className="text-sm font-semibold text-[var(--slate-500)] uppercase tracking-wide mb-3">Needs Attention</h3>
          {openTasks.length === 0 ? (
            <p className="text-sm text-[var(--slate-500)]">Nothing outstanding.</p>
          ) : (
            <ul className="space-y-2">
              {openTasks.map((t) => (
                <li key={t.id} className="flex items-center justify-between text-sm">
                  <span>{t.label}</span>
                  {t.autoGenerated && <StatusTag tone="neutral">Auto</StatusTag>}
                </li>
              ))}
            </ul>
          )}
        </Card>

        <Card className="p-4">
          <h3 className="text-sm font-semibold text-[var(--slate-500)] uppercase tracking-wide mb-3">Recent Activity</h3>
          {bundle.activity.length === 0 ? (
            <p className="text-sm text-[var(--slate-500)]">No activity yet.</p>
          ) : (
            <ul className="space-y-1.5 text-sm text-[var(--slate-700)]">
              {bundle.activity.slice(0, 8).map((a) => (
                <li key={a.id} className="flex justify-between">
                  <span>{a.message}</span>
                  <span className="text-xs text-[var(--slate-400)] font-mono-data">{new Date(a.createdAt).toLocaleDateString()}</span>
                </li>
              ))}
            </ul>
          )}
        </Card>
      </div>

      <ProductionAssistant bundle={bundle} />
    </div>
  );
}

function ProductionAssistant({ bundle }: { bundle: ProjectBundle }) {
  const [question, setQuestion] = useState("");
  const [answer, setAnswer] = useState("");
  const [loading, setLoading] = useState(false);

  const context = JSON.stringify(
    {
      project: bundle.project.name,
      status: bundle.project.status,
      shootDays: bundle.shootDays.map((d) => d.date),
      items: bundle.items.map((i) => ({ title: i.title, status: i.status, day: i.shootDayId })),
      casting: bundle.casting.map((c) => ({ role: c.characterOrRole, status: c.status })),
      locations: bundle.locations.map((l) => ({ name: l.name, status: l.status })),
      openTasks: bundle.tasks.filter((t) => t.status === "Open").map((t) => t.label),
    },
    null,
    0
  );

  async function ask() {
    if (!question.trim()) return;
    setLoading(true);
    try {
      const res = await aiService.ask(context, question);
      setAnswer(res);
    } catch {
      setAnswer("Couldn't reach the assistant.");
    } finally {
      setLoading(false);
    }
  }

  return (
    <Card className="p-4 h-fit sticky top-4">
      <h3 className="text-sm font-semibold text-[var(--slate-500)] uppercase tracking-wide mb-3">Production Assistant</h3>
      <div className="space-y-2 mb-3">
        {["What's missing for the next shoot?", "Who hasn't confirmed?", "Summarise this production."].map((q) => (
          <button
            key={q}
            onClick={() => setQuestion(q)}
            className="block text-left text-xs text-[var(--slate-500)] hover:text-[var(--slate-900)] underline decoration-dotted"
          >
            {q}
          </button>
        ))}
      </div>
      <Textarea rows={2} value={question} onChange={(e) => setQuestion(e.target.value)} placeholder="Ask about this production…" />
      <div className="flex justify-end mt-2">
        <Button size="sm" onClick={ask} disabled={loading}>{loading ? "Thinking…" : "Ask"}</Button>
      </div>
      {answer && <p className="text-sm mt-3 text-[var(--slate-700)] whitespace-pre-wrap border-t border-[var(--slate-100)] pt-3">{answer}</p>}
    </Card>
  );
}
